### PR TITLE
Add type definitions

### PR DESCRIPTION
**Pull request by DylanRJohnston**

### CODE REVIEW

**Comment by staltz** [comment]
Thanks for the PR! Could you add `callbag` as a dependency? See this template PR: https://github.com/staltz/callbag-from-promise/pull/4

**Comment by DylanRJohnston** [comment]
No worries. I also noticed going back over the code that `fromIter` accepts an `Iterable` and also an `Iterator` so I updated the types to reflect that.

**Comment by staltz** [comment]
Thank you!

**Comment by staltz** [comment]
Release 1.3.0

**Pull request merged**
